version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --save ""

  user-service-test:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3001
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      REDIS_URL: redis://redis-test:6379
      JWT_SECRET: test-jwt-secret
    ports:
      - "3001:3001"
    depends_on:
      - postgres-test
      - redis-test

  product-service-test:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3002
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      REDIS_URL: redis://redis-test:6379
    ports:
      - "3002:3002"
    depends_on:
      - postgres-test
      - redis-test

  order-service-test:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3003
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      REDIS_URL: redis://redis-test:6379
      USER_SERVICE_URL: http://user-service-test:3001
      PRODUCT_SERVICE_URL: http://product-service-test:3002
    ports:
      - "3003:3003"
    depends_on:
      - postgres-test
      - redis-test
      - user-service-test
      - product-service-test

  api-gateway-test:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3000
      REDIS_URL: redis://redis-test:6379
      USER_SERVICE_URL: http://user-service-test:3001
      PRODUCT_SERVICE_URL: http://product-service-test:3002
      ORDER_SERVICE_URL: http://order-service-test:3003
      JWT_SECRET: test-jwt-secret
    ports:
      - "3000:3000"
    depends_on:
      - redis-test
      - user-service-test
      - product-service-test
      - order-service-test
