apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  REDIS_PASSWORD: cmVkaXMxMjM=    # redis123
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  JWT_REFRESH_SECRET: eW91ci1qd3QtcmVmcmVzaC1zZWNyZXQta2V5  # your-jwt-refresh-secret-key
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5  # sk_test_your_stripe_secret_key
  EMAIL_PASSWORD: eW91ci1hcHAtcGFzc3dvcmQ=  # your-app-password
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: ecommerce
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ5b3VyLXVzZXJuYW1lIiwicGFzc3dvcmQiOiJ5b3VyLXBhc3N3b3JkIiwiYXV0aCI6ImVXOTFjaTExYzJWeWJtRnRaVHB6YjIxbExYQmhjM04zYjNKayJ9fX0=
