groups:
- name: ecommerce.recording.rules
  interval: 30s
  rules:
  # Request rate by service
  - record: ecommerce:http_requests:rate5m
    expr: |
      sum(rate(http_requests_total[5m])) by (service, method, status)

  # Error rate by service
  - record: ecommerce:http_requests:error_rate5m
    expr: |
      sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
      /
      sum(rate(http_requests_total[5m])) by (service)

  # Response time percentiles
  - record: ecommerce:http_request_duration:p95_5m
    expr: |
      histogram_quantile(0.95,
        sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)
      )

  - record: ecommerce:http_request_duration:p99_5m
    expr: |
      histogram_quantile(0.99,
        sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)
      )

  # CPU usage by pod
  - record: ecommerce:cpu_usage:rate5m
    expr: |
      sum(rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[5m])) by (pod, namespace)

  # Memory usage by pod
  - record: ecommerce:memory_usage:current
    expr: |
      sum(container_memory_working_set_bytes{container!="POD",container!=""}) by (pod, namespace)

  # Database metrics
  - record: ecommerce:database_connections:current
    expr: |
      sum(pg_stat_activity_count) by (instance)

  - record: ecommerce:database_query_time:p95_5m
    expr: |
      histogram_quantile(0.95,
        sum(rate(pg_stat_statements_mean_time_seconds_bucket[5m])) by (le, instance)
      )
